In [2]:
import seaborn as sns
import numpy as  np 
import pandas as pd 
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("../data/bronze/raw_data.csv")
df.head()

,Page Views,Session Duration,Bounce Rate,Traffic Source,Time on Page,Previous Visits,Conversion Rate
0,5,11.051381,0.230652,Organic,3.890460,3,1.0
1,4,3.429316,0.391001,Social,8.478174,0,1.0
2,4,1.621052,0.397986,Organic,9.636170,2,1.0
3,5,3.629279,0.180458,Organic,2.071925,3,1.0
4,5,4.235843,0.291541,Paid,1.960654,5,1.0

In [4]:
# Step 1: Drop irrelevant columns
df = df.drop(columns=['Conversion Rate'],axis=1)

In [5]:
num_cols = df.select_dtypes(include=['int64', 'float64'])
num_cols.corr(method='spearman')

,Page Views,Session Duration,Bounce Rate,Time on Page,Previous Visits
Page Views,1.000000,-0.007402,0.027002,0.020028,0.026353
Session Duration,-0.007402,1.000000,-0.002325,0.004357,-0.013845
Bounce Rate,0.027002,-0.002325,1.000000,0.038775,-0.006956
Time on Page,0.020028,0.004357,0.038775,1.000000,-0.039335
Previous Visits,0.026353,-0.013845,-0.006956,-0.039335,1.000000

In [6]:
#total outlier in data --- after removing Conversion rate column 

num_cols = df.select_dtypes(include=['int64','float64',]).columns
outlier_index = set()

for col in num_cols:

    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower) | (df[col] > upper)]

    print(col, ":", len(outliers))

Page Views : 21
Session Duration : 112
Bounce Rate : 13
Time on Page : 64
Previous Visits : 13

In [7]:
#uniqe  outlier row detection 
num_cols = df.select_dtypes(include=['int64','float64',]).columns
outlier_index = set()

for col in num_cols:

    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower) | (df[col] > upper)]
    
    outlier_index.update(outliers.index)

In [22]:
len(outlier_index)

216

In [8]:
# removing outliers rows

# num_cols = df.select_dtypes(include=['int64','float64',]).columns

# for col in num_cols:
    
#     Q1 = df[col].quantile(0.25)
#     Q3 = df[col].quantile(0.75)
    
#     IQR = Q3 - Q1
    
#     lower = Q1 - 1.5 * IQR
#     upper = Q3 + 1.5 * IQR
    
#     df = df[(df[col] >= lower) & (df[col] <= upper)]

In [ ]:
#cap the outlier -----Outliers ko cap kiya / clipped kiya / winsorize kiya

#Instead of removing rows, I capped the outliers using IQR boundaries so that extreme values were converted to the boundary limits.

# num_cols = df.select_dtypes(include=['int64','float64',]).columns
# for col in num_cols:

#     Q1 = df[col].quantile(0.25)
#     Q3 = df[col].quantile(0.75)

#     IQR = Q3 - Q1

#     lower = Q1 - 1.5 * IQR
#     upper = Q3 + 1.5 * IQR

#     df[col] = df[col].clip(lower, upper)

In [1]:

# num_cols = df.select_dtypes(include=['int64','float64']).columns

# plt.figure(figsize=(10,5))
# df[num_cols].boxplot()

# plt.title("Boxplot of All Numerical Columns")
# plt.show()

In [9]:
df.to_csv("../data/silver/cleaned_data.csv", index=False)